config/routes.rb
Rails.application.routes.draw do

   devise_for :users
   root 'static_pages#home'
   get 'about' => 'static_pages#about'
=begin
   get 'signup' => 'users#new'
   post 'signup' => 'users#create'

   get 'login' => 'sessions#new'
   post 'login' => 'sessions#create'
   delete 'logout' => 'sessions#destroy'
=end
   resources :posts, only: [:index, :new, :create, :show]

end

app/models/genre.rb
class Genre < ActiveRecord::Base
    delegate :user, to: :post
    belongs_to :post
    delegate  :serial, to: :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    attr_reader :body_size

    validates :title, presence: true, length: { maximum: 100 }
    validates :body, presence: true
    validate :body_token_count
    validates :user_id, presence: true                                                                            
   
    belongs_to :user
    has_many :genres
    belongs_to :serial
    has_many :reactions

    def body_token_count
      if  self.word_count > 250
            errors.add(:post, "body cannot be greater than 250 words")
        end
    end
    
    def word_count
        words = WordsCounted.count(self.body).token_count
        numbers = WordsCounted::Tokeniser.new(self.body).tokenise(pattern: /[\p{N}..]+[\p{N},.]+/).count
        words + numbers
    end
end

app/models/reaction.rb
class Reaction < ActiveRecord::Base

    belongs_to :user
    belongs_to :post
    delegate :serial, to: :post
end

app/models/serial.rb
class Serial < ActiveRecord::Base
    belongs_to :user
    has_many :posts
    has_many :genres, through: :posts
    has_many :reactions, through: :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include PostsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user[:id]
        if @post.save
            flash[:success] = "You have successfully created a post!"
            redirect_to new_post_path
        else
            render :new
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def destroy

    end

    private

    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller(not_using).rb
class SessionsController < ApplicationController
    skip_before_action :verify_authenticity_token, if: :api_request?
=begin
    def new
        if logged_in?
            redirect_to new_post_user
        end
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if (user && user.authenticate(params[:session][:password]))
            test = {success: true, user: user.userDetails}

            respond_to do |format|
                format.html {log_in user; redirect_to new_post_path}
                format.json {log_in user; render :json => test, :content_type => "text/json"}
            end
        else
            test = {success: false, error: "invalid email or password"}
            respond_to do |format|
                format.html {flash.now[:danger] = "invalid email/password"; render :new}
                format.json {render :json => test, :content_type => "text/json"}
            end
        end
    end

    def destroy
        logout
        redirect_to root_path
    end
=end
    private
    def api_request?
        request.format.json? || request.format.xml?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :verify_authenticity_token, if: :api_request?

    def new
        if logged_in?
            redirect_to new_post_user
        end
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if (user && user.authenticate(params[:session][:password]))
            test = {success: true, user: user.userDetails}

            respond_to do |format|
                format.html {log_in user; redirect_to new_post_path}
                format.json {log_in user; render :json => test, :content_type => "text/json"}
            end
        else
            test = {success: false, error: "invalid email or password"}
            respond_to do |format|
                format.html {flash.now[:danger] = "invalid email/password"; render :new}
                format.json {render :json => test, :content_type => "text/json"}
            end
        end
    end

    def destroy
        logout
        redirect_to root_path
    end

    private
    def api_request?
        request.format.json? || request.format.xml?
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def home
        if user_signed_in?
            redirect_to new_post_path
        end
    end
end

app/controllers/users_controller(not_using).rb
class UsersController < ApplicationController
    before_filter :authenticate_user!
=begin
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "You have successfully made an account"
            redirect_to new_post_path
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end
    
    private 

    #def user_params
       # params.require(:user).permit(:username, :email, :password, :password_confirmation)
    #end
=end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "You have successfully made an account"
            redirect_to new_post_path
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end
    
    private 

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
=begin
    def display_users_posts
        posts = User.find(@user[:id]).posts
        return nil if posts.count.zero?
        return posts
    end

    def display_accounts_posts
        posts = User.find(current_user[:id]).posts 
        return nil if posts.count.zero?
        return posts
    end

    def display_n_words(body, n)
        p = body.split(' ')[0..(n-1)].join(" ")
        p+= "..." if p.size != body.size
        return p
    end
=end
end

app/helpers/sessions_helper.rb
module SessionsHelper
=begin
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def logout
        session[:user_id] = nil
        @current_user = nil
    end
=end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      
      <%= link_to "MiniBlog", root_path, {:class => "navbar-brand"} %>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "MiniBlog", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li>
        
           <%= link_to root_path do%>
            <span class="glyphicon glyphicon-user"></span> <%= current_user.email %>
          <%end%>
          </li>
          <li>
          <%= link_to destroy_user_session_path do%>
            <span class="glyphicon glyphicon-user"></span> Log Out
          <%end%>

      </li>
      <% else %>
      <li>      
        <%= link_to new_user_session_path do%>
          <span class="glyphicon glyphicon-user"></span> Login
          <%end%>
        </li>
        <li>
         <%= link_to new_user_registration_path do%>
            <span class="glyphicon glyphicon-user"></span> Sign Up
          <%end%>
        </li>
        <%end%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=yield(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   
<%= render 'layouts/header' %>
<%= render 'shared/error_messages' %>
<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<% if user_signed_in? %>
    <h1> <%= current_user.email %>'s home page </h1>
    
    <center> 
    <div class="col-md-8 col-md-offset-2">
    <%= form_for(@post) do |f| %>
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control'  %>

            <%= f.label :body %>
            <%= f.text_area :body, class: 'text form-control', rows: 15, cols: 8%>

            <%= f.submit "Create Post", class: 'btn btn-primary' %>

             <div id="result"><b>
            Words: <span id="wordCount">0</span><br/></b>
        </div>
    <% end %>
    </div>
</center>
    <% else %>
        <h1> Must be logged in to create post </h1>
<% end %>

app/views/posts/show.html.erb
<div class="post">
    <h3><center><%=@post[:title] %></center></h3>
        <div id="dashed-line"></div>
<p> <%= @post[:body] %> </p>
</div>

app/views/shared/_error_messages.html.erb
<% if !@user.nil? and @user.errors %>
    <% @user.errors.each do |name, error| %>
        <li><center><%=name %>: <%=error %><center></li>
    <% end %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<p>about page</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'MiniBlogger') %>
<p>home page</p>

app/views/users/new.html.erb
<% provide(:title, "New User") %>

<h1><center>Sign Up<center></h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>

        <%= f.label :username %>
        <%= f.text_field :username, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>


        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create Account", class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user[:username]) %>

<h1> Welcome to <%= @user[:username] %>'s Profile </h1>

<% if !display_users_posts.nil? %>
   <blockquote class="accounts-posts">
        <% display_users_posts.each do |post| %>
         
                <ul>
                    <b><p><%=post[:title] %></p></b>
                </ul>
                <ul>
                    <p><%= display_n_words(post[:body], 20) %></p>
                </ul>
                <ul>
                    <p><small><%= link_to "read more...", post %></small></p>
                </ul>
                <div id="dashed-line"></div>
        <% end %>
    <blockquote>
<% else %>
    <h3> <%= @user[:username] %> has no posts </h3>
<% end %>